/* Map country names to ISO3 codes. */

const countryToId = {
  'united arab emirates': 'are',
  'afghanistan': 'afg',
  'angola': 'ago',
  'austria': 'aut',
  'australia': 'aus',
  'azerbaijan': 'aze',
  'bangladesh': 'bgd',
  'belgium': 'bel',
  'burkina faso': 'bfa',
  'bulgaria': 'bgr',
  'benin': 'ben',
  'bolivia': 'bol',
  'brazil': 'bra',
  'belarus': 'blr',
  'canada': 'can',
  'switzerland': 'che',
  'ivory coast': 'civ',
  'chile': 'chl',
  'china': 'chn',
  'colombia': 'col',
  'czech republic': 'cze',
  'germany': 'deu',
  'denmark': 'dnk',
  'dominican republic': 'dom',
  'algeria': 'dza',
  'ecuador': 'ecu',
  'egypt': 'egy',
  'spain': 'esp',
  'ethiopia': 'eth',
  'finland': 'fin',
  'france': 'fra',
  'united kingdom': 'gbr',
  'ghana': 'gha',
  'greece': 'grc',
  'guatemala': 'gtm',
  'hong kong': 'hkg',
  'honduras': 'hnd',
  'haiti': 'hti',
  'hungary': 'hun',
  'indonesia': 'idn',
  'israel': 'isr',
  'india': 'ind',
  'iran': 'irn',
  'italy': 'ita',
  'jordan': 'jor',
  'japan': 'jpn',
  'kenya': 'ken',
  'kyrgyzstan': 'kgz',
  'cambodia': 'khm',
  'south korea': 'kor',
  'laos': 'lao',
  'sri lanka': 'lka',
  'morocco': 'mar',
  'madagascar': 'mdg',
  'mali': 'mli',
  'mexico': 'mex',
  'malaysia': 'mys',
  'nigeria': 'nga',
  'nicaragua': 'nic',
  'netherlands': 'nld',
  'nepal': 'npl',
  'peru': 'per',
  'philippines': 'phl',
  'pakistan': 'pak',
  'poland': 'pol',
  'portugal': 'prt',
  'paraguay': 'pry',
  'serbia': 'srb',
  'russia': 'rus',
  'saudi arabia': 'sau',
  'sudan': 'sdn',
  'sweden': 'swe',
  'singapore': 'sgp',
  'slovenia': 'svn',
  'slovakia': 'svk',
  'senegal': 'sen',
  'el salvador': 'slv',
  'syria': 'syr',
  'thailand': 'tha',
  'tajikistan': 'tjk',
  'tunisia': 'tun',
  'taiwan': 'twn',
  'tanzania': 'tza',
  'ukraine': 'ukr',
  'uganda': 'uga',
  'united states': 'usa',
  'uzbekistan': 'uzb',
  'venezuela': 'ven',
  'vietnam': 'vnm',
  'yemen': 'yem',
  'south africa': 'zaf',
  'zambia': 'zmb'
};

export default countryToId;
