/* Map country names to ISO3 codes. */

const countryToId = {
  'United Arab Emirates': 'are',
  'Afghanistan': 'afg',
  'Angola': 'ago',
  'Austria': 'aut',
  'Australia': 'aus',
  'Azerbaijan': 'aze',
  'Bangladesh': 'bgd',
  'Belgium': 'bel',
  'Burkina Faso': 'bfa',
  'Bulgaria': 'bgr',
  'Benin': 'ben',
  'Bolivia': 'bol',
  'Brazil': 'bra',
  'Belarus': 'blr',
  'Canada': 'can',
  'Switzerland': 'che',
  'Ivory Coast': 'civ',
  'Chile': 'chl',
  'China': 'chn',
  'Colombia': 'col',
  'Czech Republic': 'cze',
  'Germany': 'deu',
  'Denmark': 'dnk',
  'Dominican Republic': 'dom',
  'Algeria': 'dza',
  'Ecuador': 'ecu',
  'Egypt': 'egy',
  'Spain': 'esp',
  'Ethiopia': 'eth',
  'Finland': 'fin',
  'France': 'fra',
  'United Kingdom': 'gbr',
  'Ghana': 'gha',
  'Greece': 'grc',
  'Guatemala': 'gtm',
  'Hong Kong': 'hkg',
  'Honduras': 'hnd',
  'Haiti': 'hti',
  'Hungary': 'hun',
  'Indonesia': 'idn',
  'Israel': 'isr',
  'India': 'ind',
  'Iran': 'irn',
  'Italy': 'ita',
  'Jordan': 'jor',
  'Japan': 'jpn',
  'Kenya': 'ken',
  'Kyrgyzstan': 'kgz',
  'Cambodia': 'khm',
  'South Korea': 'kor',
  'Laos': 'lao',
  'Sri Lanka': 'lka',
  'Morocco': 'mar',
  'Madagascar': 'mdg',
  'Mali': 'mli',
  'Mexico': 'mex',
  'Malaysia': 'mys',
  'Nigeria': 'nga',
  'Nicaragua': 'nic',
  'Netherlands': 'nld',
  'Nepal': 'npl',
  'Peru': 'per',
  'Philippines': 'phl',
  'Pakistan': 'pak',
  'Poland': 'pol',
  'Portugal': 'prt',
  'Paraguay': 'pry',
  'Serbia': 'srb',
  'Russia': 'rus',
  'Saudi Arabia': 'sau',
  'Sudan': 'sdn',
  'Sweden': 'swe',
  'Singapore': 'sgp',
  'Slovenia': 'svn',
  'Slovakia': 'svk',
  'Senegal': 'sen',
  'El Salvador': 'slv',
  'Syria': 'syr',
  'Thailand': 'tha',
  'Tajikistan': 'tjk',
  'Tunisia': 'tun',
  'Taiwan': 'twn',
  'Tanzania': 'tza',
  'Ukraine': 'ukr',
  'Uganda': 'uga',
  'United States': 'usa',
  'Uzbekistan': 'uzb',
  'Venezuela': 'ven',
  'Vietnam': 'vnm',
  'Yemen': 'yem',
  'South Africa': 'zaf',
  'Zambia': 'zmb'
};

export default countryToId;
