

const countryToId = {
  'Andorra': 'and',
  'United Arab Emirates': 'are',
  'Afghanistan': 'afg',
  'Antigua and Barbuda': 'atg',
  'Albania': 'alb',
  'Armenia': 'arm',
  'Angola': 'ago',
  'Antarctica': 'ata',
  'Argentina': 'arg',
  'Austria': 'aut',
  'Australia': 'aus',
  'Azerbaijan': 'aze',
  'Bosnia and Herzegovina': 'bih',
  'Barbados': 'brb',
  'Bangladesh': 'bgd',
  'Belgium': 'bel',
  'Burkina Faso': 'bfa',
  'Bulgaria': 'bgr',
  'Bahrain': 'bhr',
  'Burundi': 'bdi',
  'Benin': 'ben',
  'Brunei': 'brn',
  'Bolivia': 'bol',
  'Brazil': 'bra',
  'Bahamas': 'bhs',
  'Bhutan': 'btn',
  'Botswana': 'bwa',
  'Belarus': 'blr',
  'Belize': 'blz',
  'Canada': 'can',
  'Democratic Republic of the Congo': 'cod',
  'Central African Republic': 'caf',
  'Republic of the Congo': 'cog',
  'Awitzerland': 'che',
  'Ivory Coast': 'civ',
  'Chile': 'chl',
  'Cameroon': 'cmr',
  'China': 'chn',
  'Colombia': 'col',
  'Costa Rica': 'cri',
  'Cuba': 'cub',
  'Cape Verde': 'cpv',
  'Cyprus': 'cyp',
  'Czech Republic': 'cze',
  'Germany': 'deu',
  'Djibouti': 'dji',
  'Denmark': 'dnk',
  'Dominica': 'dma',
  'Dominican Republic': 'dom',
  'Algeria': 'dza',
  'Ecuador': 'ecu',
  'Estonia': 'est',
  'Egypt': 'egy',
  'Eritrea': 'eri',
  'Spain': 'esp',
  'Ethiopia': 'eth',
  'Finland': 'fin',
  'Fiji': 'fji',
  'France': 'fra',
  'Gabon': 'gab',
  'United Kingdom': 'gbr',
  'Grenada': 'grd',
  'Georgia': 'geo',
  'Ghana': 'gha',
  'Greenland': 'grl',
  'Gambia': 'gmb',
  'Guinea': 'gin',
  'Equatorial Guinea': 'gnq',
  'Greece': 'grc',
  'Guatemala': 'gtm',
  'Guinea-bissau': 'gnb',
  'Guyana': 'guy',
  'Hong Kong': 'hkg',
  'Honduras': 'hnd',
  'Croatia': 'hrv',
  'Haiti': 'hti',
  'Hungary': 'hun',
  'Indonesia': 'idn',
  'Ireland': 'irl',
  'Israel': 'isr',
  'India': 'ind',
  'Iraq': 'irq',
  'Iran': 'irn',
  'Iceland': 'isl',
  'Italy': 'ita',
  'Jamaica': 'jam',
  'Jordan': 'jor',
  'Japan': 'jpn',
  'Kenya': 'ken',
  'Kyrgyzstan': 'kgz',
  'Cambodia': 'khm',
  'Kiribati': 'kir',
  'Comoros': 'com',
  'Saint Kitts and Nevis': 'kna',
  'North Korea': 'prk',
  'South Korea': 'kor',
  'Kosovo': 'xkx',
  'Kuwait': 'kwt',
  'Kazakhstan': 'kaz',
  'Laos': 'lao',
  'Lebanon': 'lbn',
  'Saint Lucia': 'lca',
  'Liechtenstein': 'lie',
  'Sri Lanka': 'lka',
  'Liberia': 'lbr',
  'Lesotho': 'lso',
  'Lithuania': 'ltu',
  'Luxembourg': 'lux',
  'Latvia': 'lva',
  'Libya': 'lby',
  'Morocco': 'mar',
  'Monaco': 'mco',
  'Moldova': 'mda',
  'Montenegro': 'mne',
  'Madagascar': 'mdg',
  'Marshall Islands': 'mhl',
  'Macedonia': 'mkd',
  'Mali': 'mli',
  'Myanmar': 'mmr',
  'Mongolia': 'mng',
  'Macao': 'mac',
  'Mauritania': 'mrt',
  'Malta': 'mlt',
  'Mauritius': 'mus',
  'Maldives': 'mdv',
  'Malawi': 'mwi',
  'Mexico': 'mex',
  'Malaysia': 'mys',
  'Mozambique': 'moz',
  'Namibia': 'nam',
  'Niger': 'ner',
  'Nigeria': 'nga',
  'Nicaragua': 'nic',
  'Netherlands': 'nld',
  'Norway': 'nor',
  'Nepal': 'npl',
  'Nauru': 'nru',
  'Niue': 'niu',
  'New zealand': 'nzl',
  'Oman': 'omn',
  'Panama': 'pan',
  'Peru': 'per',
  'Papua New Guinea': 'png',
  'Philippines': 'phl',
  'Pakistan': 'pak',
  'Poland': 'pol',
  'Palestinian Territory': 'pse',
  'Portugal': 'prt',
  'Palau': 'plw',
  'Paraguay': 'pry',
  'Qatarw': 'qat',
  'Romania': 'rou',
  'Serbia': 'srb',
  'Russia': 'rus',
  'Rwanda': 'rwa',
  'Saudi Arabia': 'sau',
  'Solomon Islands': 'slb',
  'Seychelles': 'syc',
  'Sudan': 'sdn',
  'South Sudan': 'ssd',
  'Sweden': 'swe',
  'Singapore': 'sgp',
  'Slovenia': 'svn',
  'Slovakia': 'svk',
  'Sierra Leone': 'sle',
  'San Marino': 'smr',
  'Senegal': 'sen',
  'Somalia': 'som',
  'Suriname': 'sur',
  'Sao Tome and Principe': 'stp',
  'El Salvador': 'slv',
  'Syria': 'syr',
  'Swaziland': 'swz',
  'Chad': 'tcd',
  'Togo': 'tgo',
  'Thailand': 'tha',
  'Tajikistan': 'tjk',
  'East Timor': 'tls',
  'Turkmenistan': 'tkm',
  'Tunisia': 'tun',
  'Tonga': 'ton',
  'Turkey': 'tur',
  'Trinidad and Tobago': 'tto',
  'Tuvalu': 'tuv',
  'Taiwan': 'twn',
  'Tanzania': 'tza',
  'Ukraine': 'ukr',
  'Uganda': 'uga',
  'United States': 'usa',
  'Uruguay': 'ury',
  'Uzbekistan': 'uzb',
  'Vatican': 'vat',
  'Saint Vincent and the Grenadines': 'vct',
  'Venezuela': 'ven',
  'Vietnam': 'vnm',
  'Vanuatu': 'vut',
  'Samoa': 'wsm',
  'Yemen': 'yem',
  'South Africa': 'zaf',
  'Zambia': 'zmb'
};

export default countryToId;
